<?php
	require_once('includes/load.php');
	//include connection file
	Class dbObj{
		/* Database connection start */
		var $dbhost = "localhost";
		var $username = "root";
		var $password = "";
		var $dbname = "bank";
		var $conn;
		function getConnstring() {
			$con = mysqli_connect($this->dbhost, $this->username, $this->password, $this->dbname) or die("Connection failed: " . mysqli_connect_error());
			
			/* check connection */
			if (mysqli_connect_errno()) {
				printf("Connect failed: %s\n", mysqli_connect_error());
				exit();
				} else {
				$this->conn = $con;
			}
			return $this->conn;
		}
	}
	include_once('libs/fpdf/fpdf.php');
	class PDF extends FPDF
	{
		// Page header
		function Header()
		{
			// Logo
			#$this->Image('logo.png',10,-1,70);
			$this->SetFont('Arial','B',13);
			// Move to the right
			$this->Cell(50);
			// Title
			$this->Cell(80,10,'Accepted Leaves',1,0,'C');
			// Line break
			$this->Ln(20);
		}
		
		// Page footer
		function Footer()
		{
			$user = current_user();
			$username = $user['username'];
			// Position at 1.5 cm from bottom
			$this->SetY(-15);
			// Arial italic 8
			$this->SetFont('Arial','I',8);
			// Page number
			$this->Cell(0,10,'Page '.$this->PageNo().'/{nb} Generated by '.$username,0,0,'C');
		}
	}
	$user = current_user();
	$username = $user['username'];
	$name = $user['name'];
	$user_level = $user['user_level']; 
	
	$db = new dbObj();
	$connString =  $db->getConnstring();
	
	$header = mysqli_query($connString, "SHOW columns FROM tblleaves");
	
	if(isset($_POST['generate'])) {
		$fromdate = $_POST['fromdate'];
		$todate = $_POST['todate'];
		
		if ($user_level == 1){
			$result = mysqli_query($connString, "SELECT LeaveType, FromDate, ToDate, AdminRemarkDate FROM tblleaves WHERE PostingDate >= '$fromdate' 
AND PostingDate <= '$todate' AND status = 1 ORDER BY PostingDate ASC");
		} else {
			$result = mysqli_query($connString, "SELECT LeaveType, FromDate, ToDate, AdminRemarkDate FROM tblleaves WHERE PostingDate >= '$fromdate' 
AND PostingDate <= '$todate' AND username = '$username' AND status = 1 ORDER BY PostingDate ASC");		
		}
	
		$pdf = new PDF();
		$pdf->SetLeftMargin(14.5);
		//header
		$pdf->AddPage();
		//foter page
		$pdf->AliasNbPages();
		$pdf->SetFont('Arial','',10);
		$pdf->Cell(45,10,'Leave types',1,);
		$pdf->Cell(45,10,'From',1,);
		$pdf->Cell(45,10,'To',1,);
		$pdf->Cell(45,10,'Remark Date',1,);

		$bruh = array(35, 35, 35, 20, 50);
		
		foreach($header as $heading) {
		}
		foreach($result as $row) {
			$pdf->Ln();
					$plus = "0";
			foreach($row as $column) {
				// $pdf->Cell($bruh[$plus],10,$column,1,);
				// $plus+=1;
				 $pdf->Cell(45,8,$column,1,);
			}
		}
		$pdf->Output();
	}
?>
