<?php
    require_once('includes/load.php');
    //include connection file
    Class dbObj{
        /* Database connection start */
        var $dbhost = "localhost";
        var $username = "root";
        var $password = "";
        var $dbname = "bank";
        var $conn;
        function getConnstring() {
            $con = mysqli_connect($this->dbhost, $this->username, $this->password, $this->dbname) or die("Connection failed: " . mysqli_connect_error());
            
            /* check connection */
            if (mysqli_connect_errno()) {
                printf("Connect failed: %s\n", mysqli_connect_error());
                exit();
                } else {
                $this->conn = $con;
            }
            return $this->conn;
        }
    }
    include_once('libs/fpdf/fpdf.php');
    class PDF extends FPDF
    {
        // Page header
        function Header()
        {
            $user = current_user();
            $username = $user['username'];
            // Logo
            #$this->Image('logo.png',10,-1,70);
            $this->SetFont('Arial','B',13);
            // Move to the right
            $this->Cell(50);
            // Title
            $this->Cell(80,10,'Schedule List',1,0,'C');
            // Line break
            $this->Ln(20);
            $this->SetFont('Arial','B',8);
            $this->Cell(90,8,'Employee Username: '.$username,1,0,'L');
            // Line break
            $this->Ln(10);
        }
        
        // Page footer
        function Footer()
        {
            $user = current_user();
            $username = $user['username'];
            // Position at 1.5 cm from bottom
            $this->SetY(-15);
            // Arial italic 8
            $this->SetFont('Arial','I',8);
            // Page number
            $this->Cell(0,10,'Page '.$this->PageNo().'/{nb} Generated by '.$username,0,0,'C');
        }
    }
    $user = current_user();
    $username = $user['username'];
    $userId = (int)$_GET['id'];
    $name = $user['name'];
    $user_level = $user['user_level']; 
    
    $db = new dbObj();
    $connString =  $db->getConnstring();
    
    if ($user_level == 1){
        $result = mysqli_query($connString, "SELECT shift_type_detail,days,PostingDate,AdminRemarkDate FROM tblschedule ORDER BY id DESC");
    }
    else {
        $result = mysqli_query($connString, "SELECT shift_type_detail,days,PostingDate,AdminRemarkDate FROM tblschedule WHERE empid = '$userId' AND Status = 1 ORDER BY id DESC");
    }
    $header = mysqli_query($connString, "SHOW columns FROM tblschedule");
    
    $pdf = new PDF();
    $pdf->SetLeftMargin(14.5);
    //header
    $pdf->AddPage();
    //foter page
    $pdf->AliasNbPages();
    $pdf->SetFont('Arial','',8);
    $pdf->Cell(45,8,'Shift Time Schedule',1,);
    $pdf->Cell(45,8,'Days',1,);
    $pdf->Cell(45,8,'Posting Date',1,);
    $pdf->Cell(45,8,'Action Taken Date',1,);
    foreach($header as $heading) {
    }
    foreach($result as $row) {
        $pdf->Ln();
        foreach($row as $column)
        $pdf->Cell(45,8,$column,1,);
    }
    $pdf->Output();
?>
